### PR TITLE
Support wordlist

### PR DESCRIPTION
**Pull request by makew0rld**
## TODO

- [x] Get Microsoft and write-good styles to be enabled again, they aren't working

### CODE REVIEW

**Comment by benhylau** [comment]
Wow you got wordlist to work! Nice! I am thrilled to no longer have to learn all the ways Ubiquiti gets mispelt :D 

I see some nice catches here too in our existing doc. Excellent.

**Comment by makew0rld** [comment]
Thanks!

Styles work now, so the original functionality is matched.

**Comment by makew0rld** [comment]
@benhylau @darkdrgn2k Ready to merge if either of you can review.

Edit: If you can also check out #8 that'd be helpful.

**Review by darkdrgn2k — APPROVED** [review]

**Comment by sidd-harth0-5h4h** [comment]
Hey

**Pull request merged**
