### PR TITLE
Disable certain Vale settings

### PR DESCRIPTION
**Pull request by makew0rld**
After seeing the result in PR #4, and looking through all the options for the currently enabled styles.

I've documented by ideas on what to disable [here](https://github.com/tomeshnet/toronto-community-network/issues/71#issuecomment-672511552).

### CODE REVIEW

**Comment by benhylau** [comment]
@makeworld-the-better-one @darkdrgn2k following up on your chat convo, I am not at all bothered by the bot being picky. I agree that a word list is useful. Actually whatever is in the word list, probably make good candidates for a glossary.

For example, I'd like the tool to select either _"it is"_ or _"it's"_, and flag the other as incorrect. I think either is fine, but being inconsistent across the site is not fine. If we cannot choose one over the other, I rather we force everything to _"It's"_.

I don't have an issue with it flagging _Ubiquiti_. @YurkoWasHere I have corrected countless instances of mispelt _Ubiquiti_ over the years, and if the tool pulls it out and forces the writer to have a second read of it, I'm ok with that. Of course the better thing would be to check against a word list and flag only the mispelt ones, but in the absence of that I don't mind how it is now.

`mbps` is actually incorrect. It should be `Mbps`.

Regarding passive voice. We actually want to write not in passive voice for most of the doc, as it is used to describe something that happened in the past, whereas the bulk of our docs are current. For example, instructional docs like this, we do not want to use passive, and the tool should flag them if we do: https://dweb-camp-2019.github.io/meshnet/2.1-espressobin-router.html

@darkdrgn2k's documents actually describe an event that happened in the past, and so he used passive voice to write those. However, if we treat this as a current document, we could say:

> Supernode 1 is located on top of 200 Woolner Ave, Toronto, alongside Cisco-deployed infrastructure belonging to the City of Toronto.

instead of:

> Supernode 1 is located on top of 200 Woolner Ave, Toronto. The supernode was deployed alongside Cisco-deployed infrastructure belonging to the City of Toronto.

And...

> The router has a static IP routing to the exit node and a secondary VPS server. The secondary VPS provides an OpenVPN tunnel for secure remote management of the device.

instead of:

> Router is configured with a static IP and only routes to the exit node and a secondary VPS server. The secondary VPS is used to provide an OpenVPN tunnel for secure remote management of the device.

I think the former, non-passive voice versions, are actually easier to read. So I don't mind leaving passive voice as a warning, and updating the text to be "voice consistent".

We can probably disable `Weasel` and `TooWordy`.

**Comment by makew0rld** [comment]
> For example, I'd like the tool to select either _"it is"_ or _"it's"_, and flag the other as incorrect. I think either is fine, but being inconsistent across the site is not fine. If we cannot choose one over the other, I rather we force everything to _"It's"_.

I'm not sure if you're saying you've seen that happen, I haven't. It always seems to prefer contractions, which is good with me.

> @darkdrgn2k's documents actually describe an event that happened in the past, and so he used passive voice to write those. However, if we treat this as a current document, we could say:
> 
> > Supernode 1 is located on top of 200 Woolner Ave, Toronto, alongside Cisco-deployed infrastructure belonging to the City of Toronto.
> 
> instead of:
> 
> > Supernode 1 is located on top of 200 Woolner Ave, Toronto. The supernode was deployed alongside Cisco-deployed infrastructure belonging to the City of Toronto.

```
Supernode 1 is located on top of 200 Woolner Ave, Toronto, alongside Cisco-deplo
            ^^^^^^^^^^
"is located" may be passive voice on line 1 at column 12
```

A better phrase might start with `Supernode 1 operates on top...` or `We installed supernode 1...`. It is difficult to write in passive voice, but I understand why it could be worth it.

> We can probably disable `Weasel` and `TooWordy`.

Will do.

**Comment by benhylau** [comment]
I mean, don't allow passive voice, flag them as warnings. Passive voice is "Supernode 1 is located on top of..." and it's true that the non-passive voice sometimes is awkward "Supernode 1 operates on top...". I am saying, we should flag them as warning, but choose to leave it as "Supernode 1 is located on top of..." in cases where necessary.

**Comment by makew0rld** [comment]
Can this be merged, or does anyone disagree with what is currently being disabled?

**Review by benhylau — APPROVED** [review]

**Pull request merged**
